project:
  type: website
  output-dir: docs

website:
  title: "Nick Starcevich"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:miniproj1
      - sidebar:miniproj2

  sidebar: 
    - id: miniproj1
      title: "Maps"
      contents: 
        - part1.qmd
        - part2.qmd
        
    - id: miniproj2
      title: "Stats"
      contents: 
        - stat_project.qmd

  page-footer:
    left: |
      &copy; Nick Starcevich, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source

